### ISSUE TITLE
id already exists error on creating api and plugins 

### ISSUE THREAD

**Issue by ericln** [Mashape/kong#1623]
### Summary

We have a script that basically remove all the KONG api/plugin configuration and recreate them as we redeploy KONG to our environment via kong management api. The kong cluster has 3 nodes with postgresql database.

The issue was that we keep getting `id exists` errors randomly (during api creation or plugin creation) whenever we re-run the script on creating APIs , and sometimes plugins.  
### Steps To Reproduce
1. remove existing apis configuration
2. create each api with a script
3. create each api plugins...etc
### Additional Details & Logs
- Kong version 0.9.1
- Kong debug-level startup logs // not available, not sure how to do that with the kong docker container
- Kong error logs // na
- Kong configuration // all default plugins are enabled
- Operating System // default kong docker images

**Comment by thibaultcha** [comment]
In your docker containers, could you execute the following:
```
$ luarocks list
```

and provide us with the output?

stdout logs should be readable with:
```
$ docker logs <container-name>
```

And Kong errors logs should also be in the container, at:
```
$ cat /usr/local/kong/logs/error.log
```

If you haven't done this before, open a bash shell to a running docker container with:
```
$ docker exec -it <container> /bin/bash
```

**Comment by ericln** [comment]
`luarocks list` output

```
Warning: Failed loading manifest for /root/.luarocks/lib/luarocks/rocks: /root/.luarocks/lib/luarocks/rocks/manifest: No such file or directory

Installed rocks:
----------------

ansicolors
   1.0.2-3 (installed) - /usr/local/lib/luarocks/rocks

date
   2.1.2-1 (installed) - /usr/local/lib/luarocks/rocks

etlua
   1.3.0-1 (installed) - /usr/local/lib/luarocks/rocks

kong
   0.9.1-0 (installed) - /usr/local/lib/luarocks/rocks

lapis
   1.5.1-1 (installed) - /usr/local/lib/luarocks/rocks

loadkit
   1.1.0-1 (installed) - /usr/local/lib/luarocks/rocks

lpeg
   1.0.0-1 (installed) - /usr/local/lib/luarocks/rocks

lua-cassandra
   0.5.3-0 (installed) - /usr/local/lib/luarocks/rocks

lua-cjson
   2.1.0-1 (installed) - /usr/local/lib/luarocks/rocks

lua-resty-http
   0.08-0 (installed) - /usr/local/lib/luarocks/rocks

lua-resty-iputils
   0.2.1-1 (installed) - /usr/local/lib/luarocks/rocks

lua-resty-jit-uuid
   0.0.5-1 (installed) - /usr/local/lib/luarocks/rocks

lua_pack
   1.0.4-0 (installed) - /usr/local/lib/luarocks/rocks

lua_system_constants
   0.1.1-0 (installed) - /usr/local/lib/luarocks/rocks

luacrypto
   0.3.2-2 (installed) - /usr/local/lib/luarocks/rocks

luafilesystem
   1.6.3-2 (installed) - /usr/local/lib/luarocks/rocks

lualogging
   1.3.0-1 (installed) - /usr/local/lib/luarocks/rocks

luasec
   0.6-1 (installed) - /usr/local/lib/luarocks/rocks

luasocket
   3.0rc1-2 (installed) - /usr/local/lib/luarocks/rocks
   2.0.2-6 (installed) - /usr/local/lib/luarocks/rocks

luasyslog
   1.0.0-2 (installed) - /usr/local/lib/luarocks/rocks

luatz
   0.3-1 (installed) - /usr/local/lib/luarocks/rocks

mediator_lua
   1.1.2-0 (installed) - /usr/local/lib/luarocks/rocks

mimetypes
   1.0.0-1 (installed) - /usr/local/lib/luarocks/rocks

multipart
   0.3-2 (installed) - /usr/local/lib/luarocks/rocks

penlight
   1.3.2-2 (installed) - /usr/local/lib/luarocks/rocks

pgmoon
   1.6.0-1 (installed) - /usr/local/lib/luarocks/rocks

pgmoon-mashape
   2.0.0-1 (installed) - /usr/local/lib/luarocks/rocks

stringy
   0.4-1 (installed) - /usr/local/lib/luarocks/rocks

version
   0.2-1 (installed) - /usr/local/lib/luarocks/rocks
```

There is nothing in the `stdout`

and in the `error.logs`, just some `2016/09/11 12:43:46 [warn] 81#0: [lua] reports.lua:23: log_error(): [reports] failed to acquire ping lock: timeout, context: ngx.timer` warning, and some application type of error and buffering stuff.

**Comment by thibaultcha** [comment]
How are you deploying the 3 Kong nodes? Any chance the Nginx workers would have the same pids in several of those nodes?

**Comment by ericln** [comment]
im using kong's docker container, let me check if they have the same pid, it's possible

**Comment by ericln** [comment]
just checked they have different pids, would that cause problem if by some chance they have the same pid ?

**Comment by thibaultcha** [comment]
Yeah it would be a cause for this issue. If they don't, then I have no idea why you are seeing this behavior.

**Comment by ericln** [comment]
another behaviour we found is that if we use a new database and run the reconfiguration again (of course after re deploying the container) then the issue would go away. But again this is just so random, i'll keep an eye on the pid when we run in this issue again.

**Comment by thibaultcha** [comment]
Ok, eager to hear more about it the next time you see this.

**Comment by ericln** [comment]
yup, 

just another thought, there might be a better way to do this other than using the pid in the containerize environment.

**Comment by thibaultcha** [comment]
This has to do with the random number generator seeding, for which PIDs are perfectly fine, at least until proven otherwise, which is why it'd be really helpful to see if it is the case in your setup when the issue arises.

**Comment by pgieniec5tar** [comment]
@thibaultcha it's definitely not ideal to use pids for seeding, as it's causing us to have collisions when generating oauth2 tokens (oauth2/tokens). We are using a cluster of 6 nodes, and running into this every so often. I think it's about 15-20% of POSTS into oauth/token are causing collisions to happen.

What I would recommend, since kong uses a database already, is when the nodes register themselves into the nodes table, to just use the auto incrementing id from that table as the seed. Without adding the time to it, that will ensure the seeds are unique.

Obviously another way would be to host some sort of unique id generation service and use that, but that's definitely a more complicated solution.

Each node can't generate a unique id and ensure uniqueness in a distributed system, some kind of coordination is needed.

**Comment by pgieniec5tar** [comment]
I flipped the debug flag on error.log output and I sorted the following by seeds:

xx.xxx.77.59: 1476123507
xx.xxx.77.59: 1476123508
xx.xxx.9.89: 1476123508
xx.xxx.9.89: 1476123509
xx.xxx.158.250: 1476123512
xx.xxx.119.51: 1476123513
xx.xxx.158.250: 1476123513
xx.xxx.119.51: 1476123514
xx.xxx.13.228: 1476123514
xx.xxx.13.228: 1476123515
xx.xxx.23.56: 1476123523
xx.xxx.23.56: 1476123524
xx.xxx.77.59: 1476124654
xx.xxx.119.51: 1476124654
xx.xxx.13.228: 1476124654
xx.xxx.158.250: 1476124654
xx.xxx.23.56: 1476124654
xx.xxx.9.89: 1476124654
xx.xxx.77.59: 1476124655
xx.xxx.119.51: 1476124655
xx.xxx.13.228: 1476124655
xx.xxx.158.250: 1476124655
xx.xxx.23.56: 1476124655
xx.xxx.9.89: 1476124655

As you can see the seeds are definitely not unique, which then causes us to see the following in the error logs:

2016/10/06 07:18:11 [error] 1302#0: *732 [lua] responses.lua:101: generate_token(): [postgres error] id=already exists with value '556d1084-b844-4612-a261-6e65945a68f5', client: <some ip>, server: kong, request: "POST /oauth2/token HTTP/1.1", host: "<url>"

**Comment by thibaultcha** [comment]
@ericln,

I just pushed a hotfix to #1754 which should be applicable to `0.9.x`. We really want some feedback on it and making sure it works for other production deployments than the ones its been tested on. Do you think you'd be able to apply the provided patch and see if those go away?

Note: a behavior we saw in a production deployment is that forked VMs provide the same random bytes from `/dev/urandom` (from which OpenSSL gets its PRNG seed), since their entropy is too similar. We strongly suggest that if this is your case as well, you increase your cloned VMs entropy before starting Kong.

Much appreciated!

**Comment by evuolas** [comment]
We are also using Kong in with Docker containers running on Kubernetes cluster and we are seeing this same error when creating oauth2 access tokens. There may be tens of subsequent requests to fail and suddenly one to pass..

```
2016/11/09 19:59:35 [error] 70#0: *19570 [lua] responses.lua:101: generate_token(): [postgres error] id=already exists with value 'b8baa12f-b404-43d6-8dca-1726aedee31e', client: 111.111.11.11, server: kong, request: "POST /oauth2/token HTTP/1.1", host: "foo.bar"
```

I already updated to latest Kong version 0.9.5, but that didn't fix the problem as was suggested by @thibaultcha

**Comment by thibaultcha** [comment]
> Note: a behavior we saw in a production deployment is that forked VMs provide the same random bytes from /dev/urandom (from which OpenSSL gets its PRNG seed), since their entropy is too similar. We strongly suggest that if this is your case as well, you increase your cloned VMs entropy before starting Kong.

Please ensure that this note holds true for your setup. Since we now seed from `/dev/urandom`, there should be no such conflicts if your VMs' entropy is high enough.

**Comment by thibaultcha** [comment]
To ensure this, you can perform the following request to the admin API on each of your containers:
```
GET / HTTP/1.1
```

and retrieve the `prng_seeds` field. If any of the retrieved value is duplicated among one or several of your containers, this means that the LuaJIT PRNG was not properly seeded.

**Comment by evuolas** [comment]
Hmm, ok..

`GET / HTTP/1.1` to admin API is only returning an error to me:
```
{"message":"An unexpected error occurred"}
```

In the `error.log` I can see this:
```
2016/11/09 20:24:41 [error] 69#0: *30092 lua coroutine: runtime error: /usr/local/share/lua/5.1/kong/api/routes/kong.lua:39: attempt to index local 'kong_shm' (a nil value)
stack traceback:
coroutine 0:
        /usr/local/share/lua/5.1/kong/api/routes/kong.lua: in function </usr/local/share/lua/5.1/kong/api/routes/kong.lua:17>
coroutine 1:
        [C]: in function 'resume'
        /usr/local/share/lua/5.1/lapis/application.lua:393: in function 'handler'
        /usr/local/share/lua/5.1/lapis/application.lua:130: in function 'resolve'
        /usr/local/share/lua/5.1/lapis/application.lua:161: in function </usr/local/share/lua/5.1/lapis/application.lua:159>
        [C]: in function 'xpcall'
        /usr/local/share/lua/5.1/lapis/application.lua:159: in function 'dispatch'
        /usr/local/share/lua/5.1/lapis/nginx.lua:214: in function 'serve'
        content_by_lua(nginx.conf:143):10: in function <content_by_lua(nginx.conf:143):1>, client: 127.0.0.1, server: kong_admin, request: "GET / HTTP/1.1", host: "localhost:8001"
2016/11/09 20:24:41 [error] 69#0: *30092 [lua] init.lua:62: handle_error(): /usr/local/share/lua/5.1/lapis/application.lua:396: /usr/local/share/lua/5.1/kong/api/routes/kong.lua:39: attempt to i
ndex local 'kong_shm' (a nil value)
stack traceback:
        /usr/local/share/lua/5.1/kong/api/routes/kong.lua: in function </usr/local/share/lua/5.1/kong/api/routes/kong.lua:17>

stack traceback:
        [C]: in function 'error'
        /usr/local/share/lua/5.1/lapis/application.lua:396: in function 'handler'
        /usr/local/share/lua/5.1/lapis/application.lua:130: in function 'resolve'
        /usr/local/share/lua/5.1/lapis/application.lua:161: in function </usr/local/share/lua/5.1/lapis/application.lua:159>
        [C]: in function 'xpcall'
        /usr/local/share/lua/5.1/lapis/application.lua:159: in function 'dispatch'
        /usr/local/share/lua/5.1/lapis/nginx.lua:214: in function 'serve'
        content_by_lua(nginx.conf:143):10: in function <content_by_lua(nginx.conf:143):1>, client: 127.0.0.1, server: kong_admin, request: "GET / HTTP/1.1", host: "localhost:8001"
```

**Comment by thibaultcha** [comment]
Are you using a custom nginx configuration?

**Comment by evuolas** [comment]
Yes, I am, but server block for admin API should be identical to default configuration template. I'll double check that.

**Comment by thibaultcha** [comment]
I'm pretty sure you are missing [this](https://github.com/Mashape/kong/blob/master/kong/templates/nginx_kong.lua#L37).

**Comment by evuolas** [comment]
You were right, I had somehow missed that line. Now I got `prng_seeds` values and there are no duplicated values at the moment. I'll follow the situation and check if we still get the same errors.

Thanks!

**Comment by thefosk** [comment]
Closing this issue. Please let us know if you are still experiencing the same problem.

**Comment by akashgangil** [comment]
Hi @evuolas @thibaultcha I still get the same error trace when hitting the admin API / endpoint. I am using a custom nginx configuration but I have the line in my config.

lua_shared_dict cache 128m;

Any ideas why am I still see the error?

**Comment by thibaultcha** [comment]
@akashgangil Happy to hear. FWIW from 0.10.2-onwards we are now verifying that the required shared dictionaries are included when Kong starts, so in the future when we make modifications to those dicts, we can catch - to some extent - an incomplete custom Nginx configuration like yours.
