### ISSUE TITLE
udp-log plugin breaks "offline database mode"

### ISSUE THREAD

**Issue by stefanegg** [Mashape/kong#1784]
### Summary

When the Kong database is taken offline, the Kong node(s) usually continue to serve API requests (if I understand correctly, this is because the main configuration is cached locally). This works very well with basic API configuration and also tested with key-auth and datadog plugin added to APIs. However, as soon as the udp-log plugin is added to ANY API, Kong stops serving any API requests about 10 seconds after the DB has been taken offline, returning a HTTP 500 error ("message: An unexpected error occurred"), essentially breaking Kong's "offline database mode".

This is also described in more detail in [this](https://groups.google.com/forum/#!topic/konglayer/afRzmmT3RyA) post.

### Steps To Reproduce

1. Set up new Kong DB and node
2. Add a new API as described in https://getkong.org/docs/0.9.x/getting-started/adding-your-api
3. Call the API > everything works
4. Take the DB offline, then call the API > still works fine
5. Take the DB online again
6. Add the udp-log plugin to ANY API as described in https://getkong.org/plugins/udp-log
7. Call the API > everything works
8. Take the DB offline, then call the API > HTTP 500 after about 10 seconds

### Additional Details & Logs

- Kong version: 0.9.2
- Postgres 9.4 DB
- Tested with single Kong node as well as with 3-node setup
- No specific errors in Kong log files other than messages relating to DB host connectivity issues
`[error] 106#0: [lua] responses.lua:101: [postgres error] kong-db could not be resolved (3: Host not found), client: 172.17.0.1, server: kong_admin, request: "GET /status HTTP/1.1", host: "localhost:13888"`

**Comment by p0pr0ck5** [comment]
@stefanegg do you still see this behavior with Kong 0.10 (or 0.10.1)?

**Comment by stefanegg** [comment]
@p0pr0ck5 we do net yet have a 0.10.x installation (and stopped using the udp log plugin), however I just installed 0.10.1 on a test box and ran through the steps described above to reproduce the issue. Looks like this is working perfectly now, and has been solved somewhere along the way. Thanks for the follow-up. Closing this issue.

**Comment by p0pr0ck5** [comment]
Thanks for reporting back! :)

**Comment by faustos** [comment]
It seems that this bug is back in 0.11.x. I just run into the exact same problem with Kong 0.11.0 (docker image 0.11.0-alpine) and Postgres 9.6.
