### ISSUE TITLE
Kong + Consul DNS SRV resolving error

### ISSUE THREAD

**Issue by eltscheminov** [Mashape/kong#2333]
### Summary

Hi guys, 
I'm currently trying to integrate Kong with consul and i'm having some trouble configuring kong. Basically it is not picking the final IP (from the additional section while doing the DNS resolution). Could you guys check if it's a bug or some error of mine? Below follows the steps that i've made to get the error

### Steps To Reproduce
I've setup consul to work in a docker (ip 172.17.0.2) container and confirmed that it is working with dig command (attached below) with SRV. At the end of the dig i've got the Ip of the service 10.20.171.39 and port 3000, which is right.

After that i ran kong with DNS section pointing to 172.17.0.2 (attached below) and registered an API with a upstream url : "http://consul-app-01.service.consul."

When I try to send a request to http://kong:8000/app/ I get "An unexpected error occurred", the log shows that kong is trying to connect to an upstream server: 'http://172.17.0.2:3000' and failing, notice that 172.17.0.2 is the ip of the consul node, not the service's ip, but the port matches (my service registered with 3000). 

The DNS somehow is "working" but kong is not retrieving my service ip (kong specifically has this behavior, using dig i get the right one).

_PS: Just a reminder, i'm using the template provided from your git to get it working with docker-compose  (consul, kong, nginx and postgres)._

### Additional Details & Logs

- Kong version (`0.10.0`)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
`2017/04/04 20:42:53 [error] 75#0: *12484 connect() failed (111: Connection refused) while connecting to upstream, client: 172.17.0.4, server: kong, request: "GET /app HTTP/1.1", upstream: "http://172.17.0.2:3000/", host: "localhost:8000"`
- Kong configuration (registered APIs/Plugins & configuration file)
API Registration request:
```
"uris": [
    "/app"
  ],
  "upstream_read_timeout": 60000,
  "preserve_host": false,
  "created_at": 1490989377000,
  "upstream_connect_timeout": 60000,
  "upstream_url": "http://consul-app-01.service.consul.",
  "strip_uri": true,
  "https_only": false,
  "name": "consul-app-1",
  "http_if_terminated": true,
  "upstream_send_timeout": 60000,
  "retries": 5
}
```
Kong.conf dns part:
```
#------------------------------------------------------------------------------
# DNS RESOLVER
#------------------------------------------------------------------------------

#dns_resolver =                  # Comma separated list of nameservers, each
                                 # entry in `ipv4[:port]` format to be used by
                                 # Kong. If not specified the nameservers in
                                 # the local `resolv.conf` file will be used.
                                 # Port defaults to 53 if omitted.
dns_resolver = 172.17.0.2:53
#dns_hostsfile = /etc/hosts      # The hosts file to use. This file is read
                                 # once and its content is static in memory.
                                 # To read the file again after modifying it,
                                 # Kong must be reloaded.
```
- Operating System - CentOS Linux release 7.3.1611 (Core)

- DIG request within kong machine
```
[root@12aaab8578fb /]# dig @172.17.0.2 -p 53 consul-app-01.service.consul. SRV

; <<>> DiG 9.9.4-RedHat-9.9.4-38.el7_3.2 <<>> @172.17.0.2 -p 53 consul-app-01.service.consul. SRV
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 4215
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; QUESTION SECTION:
;consul-app-01.service.consul.	IN	SRV

;; ANSWER SECTION:
consul-app-01.service.consul. 0	IN	SRV	1 1 3000 8c09e5bcc0e1.node.dc1.consul.

;; ADDITIONAL SECTION:
8c09e5bcc0e1.node.dc1.consul. 0	IN	A	10.20.171.39

;; Query time: 9 msec
;; SERVER: 172.17.0.2#53(172.17.0.2)
;; WHEN: Tue Apr 04 21:19:21 UTC 2017
;; MSG SIZE  rcvd: 166
```

**Comment by Tieske** [comment]
Kong does not parse the `additional section` of a dns response.

It should however resolve by resolving the SRV record for `consul-app-01.service.consul` and then resolve again for `8c09e5bcc0e1.node.dc1.consul` which should result in the final A record.

What does `dig @172.17.0.2 -p 53 8c09e5bcc0e1.node.dc1.consul A` deliver?

**Comment by eltscheminov** [comment]
Hello Tieske, thank you for you response!
I managed to do what you asked and I realized that the SRV request was just returning  a wrong name, when I followed the answer with ANY I got the wrong ip (the one that Kong was following as well), even though the additional section was pointing to the right IP.

I started to dig into the consul and I found that Consul had a bug in older version that is fixed by now.

I managed to change your docker-compose template to work with this Consul new version (with the official consul image as well) and it all worked out.

Even though the error is not at the Kong side, If you will I can provide the final kong+nginxlb+consul docker-compose so you guys don't receive this kind of issue due to a consul old version.

Thank you very much for your answer!

**Comment by Tieske** [comment]
@eltscheminov A PR on the docker compose would be nice

**Comment by hutchic** [comment]
Try the `docker_overlay` branch on the docker-kong repository https://github.com/Mashape/docker-kong/pull/63

Instead of relying on consul for service discovery it leans on the docker overlay network. Also if it does work maybe :+1: this PR so we prioritize reviewing it a little higher https://github.com/Mashape/docker-kong/pull/63

**Comment by iam-merlin** [comment]
I've got the same error, when I set dns_resolver to the consul ip, my service (SRV record) is not resolved :/

@eltscheminov what did u do to make it works?

**Comment by iam-merlin** [comment]
OK... I found the error too :/
`progrium/consul:latest` is outdated :'(

**Comment by Tieske** [comment]
seems a consul bug, closing this.

**Comment by cuongnguyennc** [comment]
I'm still running into this issue, even when using the latest official consul version (instead of progrium/consul).
@eltscheminov A sample of docker-compose file would be much appreciated. Thanks in advance.
